language: java
jdk:
  - oraclejdk8
deploy:
 provider: heroku
 api-key:
  secure: 12cb7ace-d13a-4036-b888-bd0a94886f84
 app: desafio-mais-vida
after_success:
  - bash <(curl -s https://codecov.io/bash)

